[providers.node]
version = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["node prisma/prepare-db.js", "npx prisma generate --schema=prisma/schema.pg.prisma", "npx next build"]

[start]
cmd = "sh start.sh"
